foreground         #c1c3c5
background         #090F17
background_opacity 1.0
cursor             #c1c3c5

active_tab_foreground     #090F17
active_tab_background     #c1c3c5
inactive_tab_foreground   #c1c3c5
inactive_tab_background   #090F17

active_border_color   #c1c3c5
inactive_border_color #090F17
bell_border_color     #54687e

color0       #090F17
color8       #59626d
color1       #54687e
color9       #718BA8
color2       #68778b
color10      #8B9FBA
color3       #7b8799
color11      #A5B5CC
color4       #8a94a0
color12      #B9C6D6
color5       #8b98a8
color13      #BACBE1
color6       #9299a5
color14      #C3CCDD
color7       #8d9298
color15      #c1c3c5
