foreground         #c6c6c6
background         #1e1d1c
background_opacity 1.0
cursor             #c6c6c6

active_tab_foreground     #1e1d1c
active_tab_background     #c6c6c6
inactive_tab_foreground   #c6c6c6
inactive_tab_background   #1e1d1c

active_border_color   #c6c6c6
inactive_border_color #1e1d1c
bell_border_color     #6d685a

color0       #1e1d1c
color8       #767660
color1       #6d685a
color9       #928B78
color2       #78705f
color10      #A0967F
color3       #777464
color11      #9F9B86
color4       #86816c
color12      #B3AC91
color5       #938c75
color13      #C4BB9D
color6       #8b907c
color14      #BAC0A6
color7       #9d9d93
color15      #c6c6c6
